ARG BASE_IMAGE_TAG="8-slim"
FROM yusiwen/java:${BASE_IMAGE_TAG}

ARG APP_NAME="app"
ARG JAR_FILE=""

RUN mkdir -p /var/log/app && mkdir -p /var/log/skywalking

ENV PROFILE=dev_nacos \
    NACOS_HOST=nacos_server \
    PORT=8080 \
    SW_AGENT_NAMESPACE=default-namespace \
    SW_AGENT_NAME=${APP_NAME} \
    SW_AGENT_COLLECTOR_BACKEND_SERVICES=127.0.0.1:11800 \
    LOG_FILE=/var/log/app/${APP_NAME}.log \
    LOG_FILE_MAX_SIZE=50MB \
    LOG_FILE_MAX_HISTORY=100 \
    JMXREMOTE_PORT=9010 \
    JMXREMOTE_ENABLED=true \
    REMOTE_DEBUG_PORT=5005 \
    REMOTE_DEBUG_ENABLED=true \
    SW_ENABLED=false \
    JAVA_OPTS="-Xms256m -Xmx512m"

WORKDIR /app
COPY target/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["/app/entrypoint.sh"]

HEALTHCHECK --interval=1m --timeout=3s --start-period=30s \
  CMD curl -s "http://localhost:${PORT}/actuator/health"|grep UP

EXPOSE 9010
EXPOSE 5005