#!/usr/bin/env bash

echo "pre-commit: ------------------------------------------------------------"
printf "Starting format code files..."
mvn -q formatter:format impsort:sort whitespace:trim xml-format:xml-format
printf "done\n"
echo "------------------------------------------------------------------------"
